name: Production File Check

on:
  push:
    branches: [ "main" ]

jobs:
   check-production-files:
     runs-on: ubuntu-latest
     steps:
       - name: Download Code from Repo
         uses: actions/checkout@v4
       - name: List All Files
         run: ls -R
       
       - name: Verify Browser Folder Exists
         run: |
          if [ -d "browser" ]; then echo "Success: Production files are present!"
          else
            echo "Error: Production files missing!"
           exit 1
          fi
         